server:
  port: 0



spring:
  cloud:
    config:
      name: userService
      #name: ecommerce
      enabled: true
      #profile: test
  config:
      import: optional:configserver:http://localhost:8888

  #  config:
#    import: "optional:configserver:"
#  cloud:
#    config:
#      uri: http://localhost:8888/
#      name: ecommerce
#  config:
#    import: "optional:configserver:http://localhost:8888/"
#  cloud:
#    config:
#      name: ecommerce
#      profile: local
#      enabled: true


  application:
    name: user-service
  rabbitmq:
    # host: 127.0.0.1
    host: localhost
    port: 5672
    username: guest
    password: guest
  profiles:
    active: local
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/msa?characterEncoding=UTF-8&serverTimezone=UTC
#    username: root
#    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
    defer-datasource-initialization: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    com.userservice.userservice.user.client: debug

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

greeting:
  message: Welcome! How are you?


#token:
#  expiration_time: 86400000 # 60초 * 60분 * 24시간 * 1000
#  secret: user_tokenkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh

